AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: .rubocop_cache
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - "lib/wheneverd/systemd/cron_parser.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/wheneverd/systemd/cron_parser.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/wheneverd/systemd/cron_parser.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/wheneverd/systemd/cron_parser.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/wheneverd/systemd/cron_parser.rb"
