AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: .rubocop_cache
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: true
