# frozen_string_literal: true

module Wheneverd
  module Systemd
    # Shared utilities for unit file path operations.
    #
    # These methods are used by {UnitWriter}, {UnitDeleter}, {UnitLister}, and {Renderer}
    # to ensure consistent identifier sanitization, path pattern matching, and marker detection.
    module UnitPathUtils
      # Sanitizes an identifier for use in unit file names.
      #
      # Invalid characters are replaced with `-`, and consecutive/leading/trailing dashes
      # are collapsed or removed.
      #
      # @param identifier [String]
      # @return [String]
      # @raise [InvalidIdentifierError] if the identifier is empty or contains no alphanumeric chars
      def self.sanitize_identifier(identifier)
        raw = identifier.to_s.strip
        raise InvalidIdentifierError, "identifier must not be empty" if raw.empty?

        sanitized = raw.gsub(/[^A-Za-z0-9_-]/, "-").gsub(/-+/, "-").gsub(/\A-|-+\z/, "")
        if sanitized.empty?
          raise InvalidIdentifierError,
                "identifier must include at least one alphanumeric character"
        end

        sanitized
      end

      # Returns a regex pattern matching unit basenames for the given identifier.
      #
      # Matches both new-style (SHA-based) and legacy (eN-jN) unit names.
      #
      # @param identifier [String]
      # @return [Regexp]
      def self.basename_pattern(identifier)
        id = sanitize_identifier(identifier)
        /\Awheneverd-#{Regexp.escape(id)}-(?:[0-9a-f]{12}(?:-\d+)?|e\d+-j\d+)\.(service|timer)\z/
      end

      # Checks if a unit file was generated by wheneverd.
      #
      # Reads the first line of the file and checks for the marker prefix.
      #
      # @param path [String] path to the unit file
      # @return [Boolean]
      def self.generated_marker?(path)
        first_line = File.open(path, "r") { |f| f.gets.to_s }
        first_line.start_with?(Wheneverd::Systemd::Renderer::MARKER_PREFIX)
      end
    end
  end
end
